export const AVAILABLE_MODELS = [
	{
		id: 'gpt-4o-mini',
		name: 'GPT-4o Mini',
		description: 'Fast and cost-effective',
		provider: 'OpenAI',
		costTier: 'low',
		maxTokens: 1500,
		temperature: 0.3,
		capabilities: {
			textGeneration: true,
			codeGeneration: true,
			reasoning: true,
		},
	},
	{
		id: 'gpt-4o',
		name: 'GPT-4o',
		description: 'Latest multimodal model',
		provider: 'OpenAI',
		costTier: 'medium',
		maxTokens: 2000,
		temperature: 0.3,
		capabilities: {
			textGeneration: true,
			imageAnalysis: true,
			codeGeneration: true,
			reasoning: true,
		},
	},
	{
		id: 'gpt-4-turbo',
		name: 'GPT-4 Turbo',
		description: 'High performance',
		provider: 'OpenAI',
		costTier: 'high',
		maxTokens: 1800,
		temperature: 0.3,
		capabilities: {
			textGeneration: true,
			codeGeneration: true,
			reasoning: true,
		},
	},
	{
		id: 'gpt-4',
		name: 'GPT-4',
		description: 'Original GPT-4',
		provider: 'OpenAI',
		costTier: 'high',
		maxTokens: 1600,
		temperature: 0.3,
		capabilities: {
			textGeneration: true,
			codeGeneration: true,
			reasoning: true,
		},
	},
	{
		id: 'gpt-3.5-turbo',
		name: 'GPT-3.5 Turbo',
		description: 'Fast and economical',
		provider: 'OpenAI',
		costTier: 'low',
		maxTokens: 1200,
		temperature: 0.3,
		capabilities: {
			textGeneration: true,
			codeGeneration: true,
		},
	},
	{
		id: 'grok-2',
		name: 'Grok-2',
		description: 'Latest Grok model',
		provider: 'xAI',
		costTier: 'medium',
		maxTokens: 1500,
		temperature: 0.3,
		capabilities: {
			textGeneration: true,
			reasoning: true,
		},
	},
	{
		id: 'grok-2-mini',
		name: 'Grok-2 Mini',
		description: 'Smaller Grok model',
		provider: 'xAI',
		costTier: 'low',
		maxTokens: 1200,
		temperature: 0.3,
		capabilities: {
			textGeneration: true,
		},
	},
];
