version: '3.8'

services:
    # Next.js Client Application (Development)
    client-dev:
        build:
            context: .
            dockerfile: client/Dockerfile.dev
        container_name: client-dev
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - PORT=3000
            - NEXT_TELEMETRY_DISABLED=1
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/librairian_dev
            - REDIS_URL=redis://redis:6379
        volumes:
            - ./client:/app/client
            - ./shared:/app/shared
        depends_on:
            - postgres
            - redis
        networks:
            - librairian-network-dev

    # Redis Cache (Development)
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
        networks:
            - librairian-network-dev
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - redis_dev_data:/data

    # PostgreSQL Database (Development)
    postgres:
        image: postgres:16-alpine
        container_name: postgres
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=librairian_dev
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_dev_data:/var/lib/postgresql/data
            - ./prisma/sql/add_fulltext_index.sql:/docker-entrypoint-initdb.d/add_fulltext_index.sql
        networks:
            - librairian-network-dev
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5

    # pgAdmin (Development)
    pgadmin-dev:
        image: dpage/pgadmin4:latest
        container_name: pgadmin-dev
        restart: unless-stopped
        ports:
            - '5050:80'
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
            - PGADMIN_CONFIG_SERVER_MODE=False
        volumes:
            - pgadmin_dev_data:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - librairian-network-dev

volumes:
    postgres_dev_data:
    pgadmin_dev_data:
    redis_dev_data:
        driver: local

networks:
    librairian-network-dev:
        driver: bridge
