version: '3.8'

services:
    # Shared types service (base layer for other services)
    shared-types:
        build:
            context: .
            dockerfile: shared/types/Dockerfile
        volumes:
            - shared_types_dist:/app/dist
        profiles:
            - build-only

    # Next.js Client Application
    client:
        build:
            context: .
            dockerfile: client/Dockerfile
        container_name: client
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - PORT=3000
            - NEXT_TELEMETRY_DISABLED=1
            - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/librairian
        depends_on:
            shared-types:
                condition: service_completed_successfully
            postgres:
                condition: service_healthy
        networks:
            - librairian-network
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:3000',
                    '||',
                    'exit',
                    '1',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # PostgreSQL Database (Production)
    postgres:
        image: postgres:16-alpine
        container_name: postgres-prod
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=librairian
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./prisma/sql/add_fulltext_index.sql:/docker-entrypoint-initdb.d/add_fulltext_index.sql
        networks:
            - librairian-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5

    # pgAdmin (Production)
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin-prod
        restart: unless-stopped
        ports:
            - '5050:80'
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
            - PGADMIN_CONFIG_SERVER_MODE=True
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - librairian-network

networks:
    librairian-network:
        driver: bridge

volumes:
    shared_types_dist:
    postgres_data:
    pgadmin_data:
