FROM node:24-alpine3.21

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

ENV NODE_ENV=development
ENV PORT=3003
EXPOSE 3003

CMD ["npm", "run", "dev"]
